W7D2/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users

  resource :session, only: [:new, :create, :destroy]
end

W7D2/MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D2/MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    after_initialize :ensure_session_token


    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)

        # @password = password
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

end

W7D2/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?

    def log_in_user!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logout!(user)
        @current_user = nil
        session[:session_token] = nil
        user.reset_session_token!
    end

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logged_in?
        !!current_user
    end


end

W7D2/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new 
    end

    def create
        user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if user
            redirect_to users_url(user)
        else
            flash.now[:errors] = ["Invalid Credentials"]
            render :new
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

end

W7D2/MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def new
        @user = User.new
        render :new
        
    end

    def create
        @user = User.new(user_params)

        # LOGIN USERS HERE
        # if @user.save
        #     login!(@user)
        # end

    end


    private
    def user_params
        params.require(:user).permit(:email, :password)
    end
end

W7D2/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D2/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

W7D2/MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

W7D2/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if logged_in? %>
      <a href="<%= delete_session_url %>">Sign Out</a>
    <% else %>
      <a href="<%= session_url %>">Sign In</a>
      <a href="<%= new_user_url %>">Sign Up</a>
    <% end %>

  </body>
</html>

W7D2/MusicApp/app/views/users/_form.html.erb
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Email:
        <input type="text" name="user[email]">
    </label>
    <br>
    <input type="submit" value="Create User">
</form>

W7D2/MusicApp/app/views/users/index.html.erb
<h1>All of the Users</h1>
<ul>
    <% @users.each do |user|%>
        <li>
        <%= user.email %>
        </li>
    <% end %>

</ul>

W7D2/MusicApp/app/views/users/new.html.erb
<h1>New User Information</h1>
<%= render 'form', type: 'new', user: @user %>