W7D1/skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W7D1/skeleton/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
    validates :user_name, :session_token, presence: true, uniqueness: true
    validates :password, length: { minimum: 6 } 
    validates :password_digest, presence: true

    attr_reader :password

    after_initialize :ensure_session_token

    def self.find_by_credentials(user_name, password)
        user = User.find_by(user_name: user_name)
        if user && user.password?(password)
            user
        else
            nil
        end
    end



    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def password?
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end



end

W7D1/skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_url(@user.id)
    else
      render :new
    end

  end

  def new
    @user = User.new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end

end

W7D1/skeleton/app/helpers/users_helper.rb
module UsersHelper
end

W7D1/skeleton/app/views/users/_form.html.erb
<% action_url = users_url %>
<!--users_url only corresponds to POST on our routes-->
<% button_text = 'Create User' %>

<form action="<%= action_url %>" method='POST'>
  <label>Username:
    <input type="text", name="user[username]" value="">
  </label>

  <label>Password:
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up!">




</form>

W7D1/skeleton/app/views/users/new.html.erb
   <h1>New User Form</h1>
   <%= render 'form', type: 'new', user: @user %>

<!--This is where the partial variables are declared and assigned.-->
<!--The key for user: is the local variable in the partial, @user is going to be the value, which is the model instance variable-->
<!--It's not a symbol in the partial because rails uses its magic to make a variable for you.-->